server.port: 8080

spring:
  application:
    name: XiaomiAI
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomi_ai?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 20040619Lmy
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      time-to-live: 60000  # 缓存过期时间
      key-prefix: "CACHE_" # 缓存键前缀
      use-key-prefix: true # 是否使用前缀
      cache-null-values: false # 是否缓存空值
  ai:
    vectorstore:
      chroma:
        client:
          port: 9000
        collection-name: xiaomi-ai
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
