server.port: 8080

spring:
  application:
    name: XiaomiAI
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomi_ai?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 20040619Lmy
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
